apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: postgresql
  namespace: postgresql
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/postgresql
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "10.3.11"  # Set desired version
  values:
    auth:
      postgresPassword: "your_postgres_password"
      username: "your_user"
      password: "your_password"
      database: "your_database"
