apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: mongodb
  namespace: mongodb
spec:
  interval: 5m
  chart:
    spec:
      chart: bitnami/mongodb
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "12.1.0"  # Set desired version
  values:
    auth:
      rootPassword: "your_root_password"
      username: "your_user"
      password: "your_password"
      database: "your_database"
