apiVersion: kustomize.toolkit.fluxcd.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/my-cluster/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: <your-repository-name>
  targetNamespace: flux-system
  timeout: 3m
