apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m
  path: "./clusters/my-cluster/apps"
  prune: true
  sourceRef:
    kind: GitRepository
    name: github.com/balintwalter/PSAC
  targetNamespace: flux-system
  timeout: 3m
